name: Sync Git to SVN

on:
  push:
    branches: [main]

env:
  SVN_USER: ${{ secrets.SVN_USER }}
  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
  SVN_URL: ${{ secrets.SVN_URL }}

jobs:
  sync-to-svn:
    name: Sync files to SVN
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install SVN
        run: sudo apt-get install -y subversion

      - name: Setup SVN configuration
        run: |
          echo "[global]" >> ~/.subversion/servers
          echo "store-plaintext-passwords = yes" >> ~/.subversion/servers

      - name: Checkout SVN repository
        run: |
          svn checkout --username $SVN_USER --password $SVN_PASSWORD --non-interactive --trust-server-cert $SVN_URL svn-folder

      - name: List files and directories in Git repository
        id: list_git_files_dirs
        run: |
          find . -type f | sed 's|^\./||' | sort > git-files.txt
          find . -type d | sed 's|^\./||' | sort > git-dirs.txt

      - name: List files and directories in SVN repository
        id: list_svn_files_dirs
        run: |
          cd svn-folder
          svn status --no-ignore | awk '{print $2}' | sort > svn-files.txt
          find . -type d | sed 's|^\./||' | sort > svn-dirs.txt

      - name: Determine files and directories to delete from SVN
        id: files_dirs_to_delete
        run: |
          comm -23 svn-files.txt git-files.txt > files-to-delete.txt
          comm -23 svn-dirs.txt git-dirs.txt > dirs-to-delete.txt
          cat files-to-delete.txt
          cat dirs-to-delete.txt

      - name: Delete files and directories from SVN
        run: |
          cd svn-folder
          while read -r file; do
            svn rm "$file"
          done < ../files-to-delete.txt
          while read -r dir; do
            svn rm --keep-local "$dir"
          done < ../dirs-to-delete.txt
          svn commit -m "Remove files and directories not present in Git $GITHUB_SHA" --username $SVN_USER --password $SVN_PASSWORD --non-interactive --trust-server-cert

      - name: Copy files to SVN folder
        run: rsync -av --exclude '.git' . svn-folder/

      - name: Add new files and directories to SVN
        run: |
          cd svn-folder
          svn add --force * --auto-props --parents --depth infinity -q

      - name: Commit changes to SVN
        run: |
          cd svn-folder
          svn commit -m "Sync from Git $GITHUB_SHA" --username $SVN_USER --password $SVN_PASSWORD --non-interactive --trust-server-cert
